data:
  data_name: mnist
  latent_dim: 50
  n_samples: 50000
  n_samples_graph: 5000
models:
  diffusion:
    depth: 4
    dropout: 0.1
    hidden_units: 256
    time_embed_dim: 32
    use_residual: true
  encoder-decoder:
    head: CNN
    model_config: {}
training:
  diffusion:
    batch_size: 5000
    beta_bounds:
    - 0.0001
    - 0.02
    learning_rate: 0.0005
    log_interval: 100
    num_epochs: 2000
    timesteps: 1000
    weight_decay: 0.0
  encoder_decoder:
    learning_rate: 0.001
    log_interval: 10
    n_batch: 10
    num_epochs: 200
